### PR TITLE
Improve feedback message to user

### PR DESCRIPTION
**Pull request by tdurieux**

### CODE REVIEW

**Comment by gabrielRamaker** [comment]
Much nicer. Thank you. Have you ran into caching issues?

**Comment by tdurieux** [comment]
Yes, with a big json. Apparently, it was too big for data studio.

**Comment by gabrielRamaker** [comment]
My first caching implementation cached the entire request at once. But it wasn't working that well.  
The maximum cache size is 100KB, so I changed it so that each row of a dataset is cached separately. 

Probably, because of the nested data your rows exceed the 100KB limit as well

**Comment by tdurieux** [comment]
It does not surprise me that it is not working with my json file (https://durieux.me/BugSwarm-dissection/bugswarm.json). The file is 50Mb for 3000 entities... 
Without the error message, it is hard to understand what is happening, now it is better.

**Pull request merged**
