### PR TITLE
[WIP] Get recessively the fields of the JSON

### PR DESCRIPTION
**Pull request by tdurieux**
Hello,

Thanks for this useful connector, I see a lot of potentials!

I did this small change to get recessively the fields from a JSON object.

WDYT?

### CODE REVIEW

**Comment by tdurieux** [comment]
I just noticed that I forgot to update `getColumns`.

**Comment by gabrielRamaker** [comment]
Thanks a lot, that would be a great addition! I was thinking about a way to support nested data but didn't figure out how Data Studio would handle that. Have you tested your addition? 

I ran into some problems when I tested your code with a nested data source. In the createFields method your code starts with checking wether the value if an object, but because arrays are objects too it should check that as well. Furthermore in the object and array condition createField should be createField**s** 

These are my changes so far:

```
/**
 * Extract recursively the fields of the object and adds it in fields
 *
 * @param   {Object}  fields  The list of fields
 * @param   {String}  key     The key value of the current element
 * @param   {Mixed}   value   The value of the current element
 */
function createFields(fields, key, value) {
  if (typeof value === 'object' && !Array.isArray(value)) {
    Object.keys(value).forEach(function(key) {
      createFields(fields, key, value[key]);
    });
  } else if (Array.isArray(value)) {
    if (value.length > 0) {
      createFields(fields, null, value[0]);
    }
  } else if (key !== null) { // is it safe to ignore all null values or should it default to text?
    var isNumeric = !isNaN(parseFloat(value)) && isFinite(value);
    var field = isNumeric ? fields.newMetric() : fields.newDimension();

    field.setType(isNumeric ? types.NUMBER : types.TEXT);
    field.setId(key.replace(/\s/g, '_').toLowerCase());
    field.setName(key);  
  }
}
```

Unfortunately it's still returning an error within the last condition of the method. I'll see if I can debug some more at a later moment. 

If it all works I'll send a merge request tot the community-connectors project, after that it can takes a couple of days for the change to get merged.

Thanks again!

**Comment by gabrielRamaker** [comment]
I'm still in doubt wether by default adding nested fields horizontally is the best solution. It could cause field name collisions and errors with asymmetrical nested data. 

Probably it's best to make this optional by adding a newSelectSingle() to the getConfig() method, so user can choose how nested data is handle (text or inline). It should default to text in order to prevent errors.

cc.getFields() should be passed to the createFields() method to solve the error I mentioned:

```
/**
 * Extract recursively the fields of the object and adds it in fields
 *
 * @param   {Object}  fields  The list of fields
 * @param   {String}  key     The key value of the current element
 * @param   {Mixed}   value   The value of the current element
 */
function createFields(fields, types, key, value) {

  if (typeof value === 'object' && !Array.isArray(value)) {
    Object.keys(value).forEach(function(key) {
      createFields(fields, types, key, value[key]);
    });
  } else if (Array.isArray(value)) {
    if (value.length > 0) {
      createFields(fields, types, null, value[0]);
    }
  } else if (key !== null) { // is it safe to ignore all null values or should it default to text?
    var isNumeric = !isNaN(parseFloat(value)) && isFinite(value);
    var field = isNumeric ? fields.newMetric() : fields.newDimension();

    field.setType(isNumeric ? types.NUMBER : types.TEXT);
    field.setId(key.replace(/\s/g, '_').toLowerCase());
    field.setName(key);  
  }
}

/**
 * Parses first line of content to determine the data schema
 *
 * @param   {Object}  request getSchema/getData request parameter.
 * @param   {Object}  content The content object
 * @return  {Object}           An object with the connector configuration
 */
function getFields(request, content) {
  var cc = DataStudioApp.createCommunityConnector();
  var fields = cc.getFields();
  var types = cc.FieldType;
  var aggregations = cc.AggregationType;

  if (!Array.isArray(content)) content = [content];

  if (typeof content[0] !== 'object' || content[0] === null)
    sendUserError('Invalid JSON format');
  
  createFields(fields, types, null, content);

  return fields;
}
```

Furthermore it needs some work to asure unique field names and id's in this part of the code:

```
 field.setId(key.replace(/\s/g, '_').toLowerCase());
 field.setName(key);
```    

It would be nice to have the parent field name prefixed.

So, it still needs some work before it can be merged. It would be great if you could help by adding the configuration option and parent field prefix!

**Comment by tdurieux** [comment]
> It would be nice to have the parent field name prefixed.

I did some changes for handling this, I still need to do some changes to finish it

**Comment by tdurieux** [comment]
I added the option. Unfortunately, I did not succeed to set up the testing environment :/. I dont know if it is working proprely

**Comment by gabrielRamaker** [comment]
I did some debugging, but it doesn't work yet. It seems to be in a loop now. 

 I'll see if I can share my Google app project so you can do some debugging yourself as well.

**Comment by tdurieux** [comment]
Thanks a lot!

**Comment by tdurieux** [comment]
Hello,

I succeed to debug the script, it is now working for this example: https://prs.durieux.me/issues/RamonGebben/Cquence.json, in inline and text mode!

Can you try with your own data to be sure that everything is ok?

**Comment by gabrielRamaker** [comment]
Hi Thomas,

I tested it and it worked flawlessly with your dataset! When testing with my own dataset it did not work out of the box.  Incorrectly typeof null in Javascript returns 'object', so it needs to check for null values as well:

> function createFields(fields, types, key, value, isInline) {
>   if (typeof value === 'object' && !Array.isArray(value) && value !== null) {

Apart from that everything works well. Thank you for your work!

I'm going to merge your changes and add a pull request for the googledatastudio/community-connectors project.

**Comment by tdurieux** [comment]
Thanks

But It is not working with the cache :/

**Comment by gabrielRamaker** [comment]
Haven't checked that. I've added an issue for this problem. I'll try to look at it later this week.

**Pull request merged**
